import { Inter } from "next/font/google";
import { Chelsea_Market} from "next/font/google"

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const chelsea_Market= Chelsea_Market({ subsets: ["latin"],weight:['400'] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={chelsea_Market.className}>{children}</body>
    </html>
  );
}
